(() => {
 'use strict';
 const $ = s => document.querySelector(s);
 const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const records = [
  {id:1,name:'Inês Martins',email:'ines@example.com',zone:'Antebraço',style:'Botânico · Fine line',size:'12 cm',date:'2026-09-28',time:'10:00',duration:2,status:'Confirmada',idea:'Ramo de oliveira em traço fino, a preto. Composição vertical a acompanhar o antebraço.',notes:'Desenho aprovado. Rever posicionamento antes da sessão.'},
  {id:2,name:'Miguel Santos',email:'miguel@example.com',zone:'Perna',style:'Realismo · Black & Grey',size:'20 cm',date:'2026-09-28',time:'14:00',duration:3,status:'Confirmada',idea:'Retrato de um lobo com elementos de floresta. Contraste forte, sem cor.',notes:'Primeira sessão. Trazer referências impressas.'},
  {id:3,name:'Sofia Costa',email:'sofia@example.com',zone:'Braço',style:'Floral · Blackwork',size:'15 cm',date:'2026-09-29',time:'10:00',duration:2,status:'Pendente',idea:'Peónias e folhas a envolver a parte superior do braço. Gostava de discutir a composição e o tamanho.',notes:''},
  {id:4,name:'Tiago Ferreira',email:'tiago@example.com',zone:'Peito',style:'Trash Polka',size:'25 cm',date:'2026-09-30',time:'14:00',duration:3,status:'Pendente',idea:'Composição abstrata em preto e vermelho, com elementos tipográficos e pinceladas.',notes:''},
  {id:5,name:'Beatriz Silva',email:'beatriz@example.com',zone:'Costas',style:'Realismo · Black & Grey',size:'18 cm',date:'2026-10-01',time:'10:00',duration:2,status:'Pendente',idea:'Borboleta com detalhes realistas e sombras suaves. É a minha primeira tatuagem.',notes:''},
  {id:6,name:'Rita Almeida',email:'rita@example.com',zone:'Pulso',style:'Minimalista · Fine line',size:'6 cm',date:'2026-10-02',time:'11:00',duration:1,status:'Confirmada',idea:'Uma pequena flor de lótus em traço fino.',notes:'Sessão curta.'}
 ];
 const pageNames={overview:'Visão geral',agenda:'Agenda',requests:'Pedidos',clients:'Clientes',availability:'Disponibilidade'};
 let currentPage='overview', filter='Todos', selectedId=null, toastTimer;
 const days=['2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02'];
 const blocked = new Set();
 const dateLabel = date => new Date(date+'T12:00:00').toLocaleDateString('pt-PT',{day:'numeric',month:'short'});
 const initials = name => name.split(' ').slice(0,2).map(n=>n[0]).join('');
 const badge = r => `<span class="pill ${r.status==='Confirmada'?'confirmed':r.status==='Cancelada'?'cancelled':''}">${escape(r.status)}</span>`;
 const toast = text => {clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);};
 const heading = (title,desc,action=true) => `<div class="page-heading"><div><div class="eyebrow">MÁXIMO’S / ESTÚDIO PRIVADO</div><h2>${title}</h2><p>${desc}</p></div>${action?'<button class="primary" data-new>＋ Nova marcação</button>':''}</div>`;
 const requestRow = r => `<button class="request-row" data-record="${r.id}"><span class="avatar">${initials(r.name)}</span><span class="request-text"><strong>${escape(r.name)}</strong><small>${escape(r.style)} · ${dateLabel(r.date)}</small></span><span>↗</span></button>`;
 const endTime = r => String(Number(r.time.split(':')[0])+Number(r.duration)).padStart(2,'0')+':'+r.time.split(':')[1];
 const appointment = r => `<div class="appointment"><div class="appointment-time">${r.time}<small>${endTime(r)}</small></div><span class="appointment-line"></span><div><strong>${escape(r.name)}</strong><p>${escape(r.style)} · ${escape(r.zone)}</p>${badge(r)}</div><button data-record="${r.id}" aria-label="Abrir ficha de ${escape(r.name)}">↗</button></div>`;
 function render(){
  $('#breadcrumb').textContent=pageNames[currentPage];
  document.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===currentPage);if(b.closest('nav')){if(b.dataset.page===currentPage)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}});
  const pending=records.filter(r=>r.status==='Pendente');const confirmed=records.filter(r=>r.status==='Confirmada');
  $('#nav-count').textContent=pending.length;
  let html='';
  if(currentPage==='overview')html=heading('Bom dia, Bruno.','Segunda-feira, 28 de setembro de 2026 · Vamos criar algo único.')+`<div class="stats"><div class="stat"><div class="stat-label">Sessões de hoje <span>↗</span></div><div class="stat-value">${confirmed.filter(r=>r.date===days[0]).length.toString().padStart(2,'0')}</div><small>Na agenda do estúdio</small></div><div class="stat"><div class="stat-label">Pedidos pendentes <span>↙</span></div><div class="stat-value">${pending.length.toString().padStart(2,'0')}</div><small>À espera da tua resposta</small></div><div class="stat"><div class="stat-label">Sessões nesta semana <span>▦</span></div><div class="stat-value">${confirmed.filter(r=>days.includes(r.date)).length.toString().padStart(2,'0')}</div><small>Marcações confirmadas</small></div></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h3>A tua agenda de hoje</h3><p>28 setembro · Segunda-feira</p></div><button class="text-button" data-page="agenda">Ver agenda ↗</button></div>${confirmed.filter(r=>r.date===days[0]).map(appointment).join('')||'<div class="empty">Sem sessões para hoje.</div>'}</section><section class="panel"><div class="panel-head"><div><h3>Novas ideias a chegar</h3><p>Pedidos por confirmar</p></div><span class="pill">${pending.length} novos</span></div>${pending.slice(0,3).map(requestRow).join('')||'<div class="empty">Todos os pedidos foram tratados.</div>'}</section></div><div class="studio-note"><div><h3>Um estúdio ao teu ritmo.</h3><p>Define os dias em que recebes novos projetos e reserva tempo para criar.</p></div><button class="secondary" data-page="availability">Gerir disponibilidade ↗</button></div>`;
  if(currentPage==='requests')html=heading('Cada tatuagem começa com uma ideia.','Consulta os pedidos e confirma os próximos projetos.')+`<div class="filters">${['Todos','Pendente','Confirmada','Cancelada'].map(s=>`<button data-filter="${s}" class="${filter===s?'selected':''}" aria-pressed="${filter===s}">${s==='Todos'?'Todos':s==='Pendente'?'Pendentes':s==='Confirmada'?'Confirmados':'Cancelados'}</button>`).join('')}</div><div class="panel"><div class="table-head"><span>CLIENTE</span><span>PROJETO</span><span>DIA PREFERIDO</span><span>ESTADO</span><span></span></div>${records.filter(r=>filter==='Todos'||r.status===filter).map(r=>`<button class="table-row" data-record="${r.id}"><span>${escape(r.name)}<small>${escape(r.email)}</small></span><span>${escape(r.style)}<small>${escape(r.zone)} · ${escape(r.size)}</small></span><span>${dateLabel(r.date)}<small>${r.status==='Pendente'?'Horário a confirmar':r.time}</small></span><span>${badge(r)}</span><span>↗</span></button>`).join('')||'<div class="empty">Sem pedidos neste estado.</div>'}</div>`;
  if(currentPage==='agenda')html=heading('Espaço para a tua arte.','28 setembro — 2 outubro 2026 · Semana de demonstração')+`<div class="week-grid">${days.map((d,i)=>`<section class="day-column"><div class="day-label">${['Segunda','Terça','Quarta','Quinta','Sexta'][i]}<strong>${d.slice(-2)}</strong></div>${confirmed.filter(r=>r.date===d).sort((a,b)=>a.time.localeCompare(b.time)).map(r=>`<button class="session-card" data-record="${r.id}">${r.time} — ${endTime(r)}<strong>${escape(r.name)}</strong><small>${escape(r.style)}</small></button>`).join('')||`<div class="empty">${blocked.has(d)?'Indisponível para novos pedidos':'Sem sessões confirmadas'}</div>`}</section>`).join('')}</div><p class="muted" style="margin-top:20px;font-size:12px">Os pedidos pendentes ficam na área Pedidos até serem confirmados.</p>`;
  if(currentPage==='clients')html=heading('Pessoas, histórias e projetos.','Fichas de exemplo com contactos e ideias.',false)+`<div class="client-grid">${records.map(r=>`<button class="panel client-card" data-record="${r.id}"><span class="avatar">${initials(r.name)}</span><h3>${escape(r.name)}</h3><p>${escape(r.email)}</p><p>${escape(r.style)}</p><span>Abrir ficha ↗</span></button>`).join('')}</div>`;
  if(currentPage==='availability')html=heading('A agenda é tua.','Escolhe os dias abertos a novos pedidos. As sessões existentes mantêm-se.',false)+`<section class="panel availability">${days.map((d,i)=>`<div class="availability-row"><div>${['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira'][i]} · ${dateLabel(d)}<small>Horário do estúdio: 10:00 — 18:00</small></div><label><input type="checkbox" data-available="${d}" ${blocked.has(d)?'':'checked'}> Disponível para pedidos</label></div>`).join('')}</section><p class="muted" style="margin-top:20px;font-size:12px">Alterações simuladas nesta sessão de apresentação.</p>`;
  $('#main').innerHTML=html;
 }
 function openRecord(id){selectedId=Number(id);const r=records.find(r=>r.id===selectedId);if(!r)return;$('#detail-content').innerHTML=`<h2>${escape(r.name)}</h2><div class="dialog-subtitle">${escape(r.style)} · ${badge(r)}</div><div class="detail-facts"><div><small>EMAIL</small><span>${escape(r.email)}</span></div><div><small>DIA ${r.status==='Pendente'?'PREFERIDO':'DA SESSÃO'}</small><span>${dateLabel(r.date)} 2026</span></div><div><small>ZONA DO CORPO</small><span>${escape(r.zone)}</span></div><div><small>TAMANHO APROXIMADO</small><span>${escape(r.size)}</span></div></div><div class="eyebrow">A IDEIA</div><p class="idea">${escape(r.idea)}</p><label>Notas privadas<textarea id="record-notes" maxlength="2000" placeholder="Notas sobre este projeto…">${escape(r.notes)}</textarea></label><div class="form-grid"><label>Hora<input id="record-time" type="time" value="${r.time}" ${r.status!=='Pendente'?'disabled':''}></label><label>Duração<select id="record-duration" ${r.status!=='Pendente'?'disabled':''}>${[1,2,3].map(n=>`<option value="${n}" ${Number(r.duration)===n?'selected':''}>${n} ${n===1?'hora':'horas'}</option>`).join('')}</select></label></div><div class="dialog-actions"><button class="secondary" id="save-notes">Guardar notas</button>${r.status==='Pendente'?'<button class="primary" id="confirm-record">Confirmar marcação ↗</button>':''}${r.status!=='Cancelada'?'<button class="text-button" id="cancel-record">Cancelar marcação</button>':''}</div>`;$('#detail-dialog').showModal();}
 function conflict(date,time,duration,exclude){const minutes=t=>Number(t.split(':')[0])*60+Number(t.split(':')[1]);const start=minutes(time),end=start+Number(duration)*60;return records.some(r=>r.id!==exclude&&r.status==='Confirmada'&&r.date===date&&start<minutes(r.time)+Number(r.duration)*60&&end>minutes(r.time));}
 $('#login-form').addEventListener('submit',e=>{e.preventDefault();$('#login').hidden=true;$('#app').hidden=false;render();window.scrollTo(0,0);});
 $('#show-password').onclick=()=>{const visible=$('#password').type==='password';$('#password').type=visible?'text':'password';$('#show-password').textContent=visible?'Ocultar':'Mostrar';$('#show-password').setAttribute('aria-label',visible?'Ocultar palavra-passe':'Mostrar palavra-passe');};
 $('#recover').onclick=()=>toast('Demonstração: aqui receberias um email para recuperar o acesso.');
 $('#logout').onclick=()=>{$('#app').hidden=true;$('#login').hidden=false;toast('Sessão de demonstração terminada.');};
 document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){currentPage=page.dataset.page;render();window.scrollTo({top:0,behavior:"instant"});}const row=e.target.closest('[data-record]');if(row)openRecord(row.dataset.record);if(e.target.closest('[data-new]'))$('#new-dialog').showModal();if(e.target.closest('[data-close]'))e.target.closest('dialog').close();const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();}if(e.target.id==='save-notes'){records.find(r=>r.id===selectedId).notes=$('#record-notes').value;toast('Notas guardadas nesta demonstração.');}if(e.target.id==='confirm-record'){const r=records.find(r=>r.id===selectedId),time=$('#record-time').value,duration=Number($('#record-duration').value);if(!time){toast('Escolhe uma hora para a sessão.');return;}if(blocked.has(r.date)){toast('Este dia está indisponível. Abre-o na área Disponibilidade.');return;}if(time<'10:00'||Number(time.split(':')[0])+Number(time.split(':')[1])/60+duration>18){toast('Escolhe uma sessão entre as 10:00 e as 18:00.');return;}if(conflict(r.date,time,duration,r.id)){toast('Já existe uma sessão nesse horário. Escolhe outra hora.');return;}Object.assign(r,{status:'Confirmada',time,duration,notes:$('#record-notes').value});$('#detail-dialog').close();render();toast('Marcação confirmada. O email ao cliente é apenas simulado.');}if(e.target.id==='cancel-record'){const r=records.find(r=>r.id===selectedId);r.status='Cancelada';$('#detail-dialog').close();render();toast('Marcação cancelada nesta demonstração.');}});
 document.addEventListener('change',e=>{if(e.target.matches('[data-available]')){e.target.checked?blocked.delete(e.target.dataset.available):blocked.add(e.target.dataset.available);toast('Disponibilidade atualizada nesta demonstração.');}});
 $('#new-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(blocked.has(data.date)){toast('Este dia está indisponível.');return;}if(data.time<'10:00'||Number(data.time.split(':')[0])+Number(data.time.split(':')[1])/60+Number(data.duration)>18){toast('Escolhe uma sessão entre as 10:00 e as 18:00.');return;}if(conflict(data.date,data.time,data.duration)){toast('Já existe uma sessão nesse horário. Escolhe outra hora.');return;}records.push({...data,id:Date.now(),name:data.name.trim(),style:'Projeto personalizado',size:'A definir',status:'Confirmada',notes:''});$('#new-dialog').close();e.target.reset();currentPage='requests';filter='Confirmada';render();toast('Marcação adicionada nesta demonstração.');};
})();

